[package]
name = "voltage-jit"
version = "0.1.0"
edition = "2021"

[dependencies]
voltage-core = { path = "../voltage-core" }
cranelift = "0.106"
cranelift-jit = "0.106"
cranelift-module = "0.106"
cranelift-codegen = "0.106"